### ISSUE TITLE
Create a new release from master

### ISSUE THREAD

**Issue by SebastianSzturo** [yakaz/yamerl#11]
I am trying to get yamerl into Elixir's hex through the community repository [hexpm/community](https://github.com/hexpm/community). But we have to provide a tag release to get it correctly in the repository. The ```v0.3.1-1``` release still has the OTP 18.0 dict deprecation warnings. 
Could you please create a new tag release from master?

**Comment by dumbbell** [comment]
I'm sorry for the delay to handle this, but at last, 0.3.2 is tagged!

**Comment by SebastianSzturo** [comment]
Thank you so much for this great library and for maintaining this repository. :)
