### ISSUE TITLE
Missing configure.ac file for Mix support

### ISSUE THREAD

**Issue by gmalkas** [yakaz/yamerl#12]
Hey,

I'm trying to compile yamerl from the Hex package provided (https://hex.pm/packages/yamerl) but there is an error when running `mix deps.compile yamerl`:

```bash
==> yamerl (compile)
ERROR: sh(awk '/^AC_INIT\(/ { ver=$0; sub(/AC_INIT\(\[[^]]+\], *\[/, "", ver); sub(/\].*/, "", ver); print ver; } { next; }' configure.ac)
failed with return code 2 and the following output:
awk: fatal: cannot open file `configure.ac' for reading (No such file or directory)
```

Looking at https://github.com/yakaz/yamerl/blob/master/package.exs#L22, it seems that `configure.ac` is missing.

Thanks!

**Comment by BennyHallett** [comment]
+1 I'm having the same issue

**Comment by gmalkas** [comment]
Adding the missing file to the hex package solved the issue for me. Turns out I will not need yamerl for my project after all but the fix is pretty straightforward.

**Comment by dumbbell** [comment]
Thanks for the report and sorry for the delay to get back to you...

I added `configure.ac` to the list. Could you please confirm that it works now?

**Comment by gmalkas** [comment]
:+1:  I just tried with a new mix project and yamerl master, compiled like a charm.

Thanks!

**Comment by gmalkas** [comment]
I reopened the issue because I thought you might want to close it when you release new version to Hex.

**Comment by SebastianSzturo** [comment]
As mentioned in #11, we need a tagged git release to update the mix project. 
@dumbbell Could you please create a new git tag please? :)
