### ISSUE TITLE
Blocks when parsing "test:"

### ISSUE THREAD

**Issue by davidmoreno** [yakaz/yamerl#14]
Used from elixir (I don't think it matters), but when executing:

```elixir
iex> :yamerl.decode("test:")
```
or
```elixir
iex> :yamerl_constr.string("test:") 
```

It blocks forever, using 100% CPU.

It should return some kind of error about invalid YAML, or an object with .

For comparison, Python's yaml module, returns: `{'test':None}`

**Comment by dumbbell** [comment]
Thank you for the bug report!
