### ISSUE TITLE
Trivial Untrusted DoS vuln

### ISSUE THREAD

**Issue by steakknife** [yakaz/yamerl#18]
**Version** 0.4.0. This means affecting hex packages and other packages like yaml_elixir.

**Impact** Launching observer, it shows consuming all CPU by running in infinite loop and growing memory without bound.

**Vuln** For responsible disclosure practices, an email address with an associated GPG public key  ([maybe one of these](https://pgp.mit.edu/pks/lookup?search=jean-sebastien.pedron%40dumbbell.fr&op=index)) is needed to transfer specifics. If no reply is made, it will be publicly disclosed 2 months from today.

**Comment by steakknife** [comment]
Confirmed on master as well.

**Comment by steakknife** [comment]
I've manually reduced the pattern-space, and have some eunit tests.

It seems wise to consider QuickCheck/Mini, PropEr or other property/type fuzzing because YAML is complex and difficult to get right (400+ hits on CVEMITRE).

**Comment by dumbbell** [comment]
Hi!

Thank you for doing this analysis. You can reach me at one of the uids of [my PGP key](https://pgp.mit.edu/pks/lookup?op=vindex&search=0xD938F9C86816981C).

**Comment by steakknife** [comment]
Will do daytime.

Looked at [QuickCheck Mini](https://github.com/rpt/eqcmini)* for property testing. Fuzzing utf8/16/32, lexical, syntactic and document levels seems to make sense.

\* [EULA is short](https://htmlpreview.github.io/?https://raw.githubusercontent.com/rpt/eqcmini/master/LicenceAgreement.html) isn't too awful (not BSD) and the reducer is superior compared to triq and PropEr.

[More QuickCheck packages](http://hypothesis.works/articles/quickcheck-in-every-language/)

**Comment by steakknife** [comment]
Email sent.

**Comment by steakknife** [comment]
[Here's an expanded EUnit test for this issue](https://bitbucket.org/barry_allard/yamerl/src/6d475e5ccdbf67f0e2e11bb99ed67de1cb90843a/test/yamerl_constr_test.erl?fileviewer=file-view-default) (deep-link to a private repo)

**Comment by steakknife** [comment]
LGTM 🍻

Also, would it be possible to get a release bump for downstream packages and app deps?
