### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by lucafavatella** [yakaz/yamerl#28]
Hi,

Any specific reasons why the v0.6.0 tag is marked as "latest release" in github when the 0.7.0 tag is present and apparently in good shape? I assume you just forgot to mark 0.7.0 as latest release though I am checking.

I see both 0.6.0 and 0.7.0 passed CI. I see 0.7.0 is on hex.pm .

Thanks for the useful library!

**Comment by dumbbell** [comment]
Hi!

Yes, that's a leftover. Thanks!
