### ISSUE TITLE
Length of term or ending position

### ISSUE THREAD

**Issue by jjl** [yakaz/yamerl#30]
I'm using yaml for configuration and it would be awesome to be able to highlight the term that is incorrect in a listing of the user's yaml file.

This requires one of:
- a length in bytes that the term occupies in yaml form
- an ending position for the term

Is there an appetite for such a change? Would it be difficult to make? Would you be likely to accept a PR?

Cheers,
James

**Comment by dumbbell** [comment]
Hi! Almost two years to respond, sorry...

Yamerl can provide details about the position of a specific token (both start and end), including errors. Look at the [detailed construction mode](https://hexdocs.pm/yamerl/yamerl_constr.html#new-2).

I believe you can achieve what you want with that. If you have improvements in mind, they are welcome!
