### ISSUE TITLE
Infinite loop on empty yaml document

### ISSUE THREAD

**Issue by jansenm** [yakaz/yamerl#36]
Hi

I am not really sure thats valid yaml but ansible for example has no problem with this syntax.
```elixir
  test "timeout in yamerl" do
    task = Task.async(
      fn ->
        :yamerl_constr.string("")
      end
    )
    Task.await(task)
  end

  test "timeout in yamerl 2" do
    task = Task.async(
      fn ->
        :yamerl_constr.string("---")
      end
    )
    Task.await(task)
  end
```

A file just with the document marker on top (required by some editors to recognize the file type) leads to a infinite loop somehow. An empty document without the the document marker works.

**Comment by dumbbell** [comment]
Hi! Sorry to get back to you after so many months...

I can't reproduce locally. I'm going to add a testcase to check the situation. If you are still interested in this issue, could you please run the testsuite locally?

**Comment by jansenm** [comment]
Cant reproduce anymore either. Perhaps it was an incompatibility with some older elixir code? I actually checked this three times because i was pretty new bad than and always thought i am doing something wrond.

anyway. not happending anymore. closing
