### ISSUE TITLE
Duplicate key allowed in map

### ISSUE THREAD

**Issue by slezakattack** [yakaz/yamerl#39]
According to the YAML spec (https://yaml.org/spec/1.2/spec.html#id2802432), one of "maps" properties is to possess unique keys.

Discovered a bug that yamerl allows multiple keys when map is proplist and/or {detailed_constr, true} is set.

I have a PR to address the bug along with a test coming soon.

**Comment by ronaldwind** [comment]
I would like to see this change merged. Is there any update for this issue? @dumbbell?

**Comment by dumbbell** [comment]
Thanks for the direct ping, I don't get other notifications apparently...

After looking at the patch, it needs some improvements. For instance, it only works if the key is a scalar in `detailed_constr` mode. I will look into it in the coming days and keep you posted.

**Comment by flurin** [comment]
@dumbbell Is there an update on this issue? Anything that can be done to help with this?

**Comment by dumbbell** [comment]
Thank you for the ping, I copmpletly forgot about this and missed again the latest change made by @slezakattack... Working on this right now!

**Comment by flurin** [comment]
Awesome! Thank you. Any chance that could be added to a release?

**Comment by dumbbell** [comment]
Yes. I'm waiting a day or two for answers on other issues/pull requests, then I will cut a release.

**Comment by dumbbell** [comment]
@flurin: I just [published yamerl 0.9.0 to Hex.pm](https://hex.pm/packages/yamerl/0.9.0).

Thank you for your patience!

**Comment by flurin** [comment]
Excellent, thank you!

**Comment by bobkocisko** [comment]
Oh no!  I realize I'm late to the party here but we were relying on the duplicate key "feature" when in detailed_const mode to (ab)use the yaml syntax and create a much (c)leaner dsl for our purposes.  

Is there any chance that you would consider wrapping these new changes under a configuration switch, to still support the old behavior while keeping the new behavior as default?  Something like `{allow_dupkeys , true}` @dumbbell 

I feel that it is reasonable in detailed_const mode to support invalid yaml.  As I see it this provides a complete view of the document even if it is invalid in this way, which the developer can use or discard as needed.

**Comment by dumbbell** [comment]
Yes, I can introduce that option, @bobkocisko. I filed an issue for that (#52).

**Comment by bobkocisko** [comment]
Thank you!
