### ISSUE TITLE
Unclosed inline map fails entire document silently

### ISSUE THREAD

**Issue by bobkocisko** [yakaz/yamerl#43]
Hello!  Thanks for this great library!  I'm using this from Elixir and came across this issue:

```
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :yamerl_constr.string("{a: 2}")
[[{'a', 2}]]
iex(2)> :yamerl_constr.string("{a: 2")  
[]
iex(3)>
```

Normally parse errors throw an exception but no exception is thrown here.

Yamler version 0.8.1

**Comment by dumbbell** [comment]
Hi!

Thank you for the bug report! I prepared a patch in the pull request mentionned above. Does it work for you?

**Comment by bobkocisko** [comment]
Very cool!  I can't try it just now but I'll let you know as soon as I get back to that (may be a few months)

**Comment by dumbbell** [comment]
Let's be optimistic :-) I merged the patch and will cut a release shortly. If you still hit a problem, please re-open this issue!
