### ISSUE TITLE
_build/default/lib/yamerl/include/internal/yamerl_constr.hrl:30: can't find include file "yamerl_nodes.hrl"

### ISSUE THREAD

**Issue by ElectronicRU** [yakaz/yamerl#44]
Includes in yamerl are kinda woky and only work because rebar3 explicitly adds app/include to private include libraries.
When attempting to include them from another application, which is necessary in order to write a custom node module (no access to ext_options otherwise!), it explodes.

Possible solutions:
- Use -include("../yamerl_nodes.hrl")
- Use -include_lib("yamerl/include/yamerl_nodes.hrl").

**Comment by dumbbell** [comment]
Hi!

Thank you for the suggestion! Does the proposed patch works for you?

**Comment by dumbbell** [comment]
Fixed by #54.
