### ISSUE TITLE
Add an option to allow duplicate keys in mappings

### ISSUE THREAD

**Issue by dumbbell** [yakaz/yamerl#52]
yamerl 0.9.0 fixed the situation where duplicate keys in mappings were not checked, and thus allowed. Some users relied on that behavior, even though it is invalid from a YAML specification point of view.

Both behaviors should be fine and there should be an option to enable the old behavior, meaning that duplicate keys would be kept when the constructure structure permits it.

See #39 and [@bobkocisko comment](https://github.com/yakaz/yamerl/issues/39#issuecomment-1012382959).

**Comment by flurin** [comment]
I expect the change that fixes #39 to return an error instead of just taking the last key. As this is not the case we would very much like to have an option to enable the old behaviour again (especially useful in comination with the `detailed_constr` option.)

**Comment by flurin** [comment]
@dumbbell I have created the #53 PR to add the option. This is my first bit of Erlang code so I hope it is up to par. Let me know what you think / what needs improvement to get this merged.

**Comment by dumbbell** [comment]
@flurin: Thank you so much! I will add further comments to the pull request directly.
