### ISSUE TITLE
Multiple documents and TAG directive won't parse

### ISSUE THREAD

**Issue by jdewar** [yakaz/yamerl#55]
I can't get this test string to parse:
```
test_string = """
%YAML 1.1
%TAG !u! tag:custom:
--- !u!100
Document1:
  one: 1
--- !u!101
Document2:
  two: 2
"""
```

Attempting to ignore the tags works for the first prefix, but not the second:
``` elixir
> :yamerl_constr.string(test_string, detailed_constr: true, ignore_unrecognized_tags: true)

** (throw) {:yamerl_exception, [{:yamerl_parsing_error, :error, ~c"Tag handle \"!u!\" never declared", 6, 11, :undeclared_tag_handle, {:yamerl_tag, 6, 5, ~c"!u!101"}, []}]}
```

Attempting to define the custom tags (forgive my use of YamlElixir here, but it's how I was able to move forward) also shows that the second document can't resolve the prefix, even when not ignoring unrecognized tags:
``` elixir
defmodule CustomNode do
  def tags, do: for(id <- 100..101, do: ~c"tag:custom:#{id}")

  def construct_token(constr, node, value) do
    :yamerl_node_map.construct_token(constr, node, value)
  end

  def node_pres(node), do: :yamerl_node_map.node_pres(node)
end
:yamerl_app.set_param(:node_mods, [CustomNode])

> YamlElixir.read_all_from_string!(test_string)

** (YamlElixir.ParsingError) Tag "!u!101" unrecognized by any module (line: 6, column: 5)
    (yaml_elixir 2.9.0) lib/yaml_elixir.ex:32: YamlElixir.read_all_from_string!/2
```

**Comment by dumbbell** [comment]
Hi!

It's unclear to me from the YAML 1.2 spec what the scope of tags is. It says that a directive (including tag definitions) applies to the following document, but on the other hand, it does not say that it shouldn't apply to all following documents. It doesn't say either that a "directive end marker" or a "document end marker" reset the defined tags.

Do you say that other parser keep defined tags for all subsequent documents?

**Comment by jdewar** [comment]
Yeah, with some distance and coming back to try to answer this question I realize now that ruby's yaml parser also doesn't handle that document with the same error.  What I have is [UnityYAML](https://docs.unity3d.com/Manual/UnityYAML.html) and I didn't realize how different it was.

in the examples of the spec, [Example 2.24. Global Tags](https://yaml.org/spec/1.2.0/) it shows 'global' tags, but does not show then extending across documents.  I'm gonna close this as I have no evidence it should be supported.
